"""Appends "nearest emergency hospital" info to an emergency reply, using the
patient's own device coordinates (sent by the frontend only at the moment a message
is about to be shown as an emergency reply — see app.schemas.chat.ChatRequest).

Data source is OpenStreetMap's public Overpass API — free, keyless, no signup, no
billing. Trade-off vs. a paid provider (Google Places etc.): coverage/data quality
varies by region, and a phone number isn't always tagged on a given hospital node.
Chosen anyway per product decision: this is a bolt-on convenience, not the emergency
instruction itself (the existing "call 1122" guidance already covers the safety-
critical part), so a paid API key is not worth the added operational cost.

Deliberately never allowed to block or degrade the actual emergency reply: a short
timeout, and ANY failure (no coordinates given, network error, empty result) simply
means the caller appends nothing — the emergency message text already fully stands
on its own without this block. Never generated by the LLM (same "don't trust the
LLM alone for a safety-critical fact" pattern as red_flag.py and appointment_agent's
doctor-name resolution) — this is a plain deterministic lookup + string format.
"""
import math

import httpx

_OVERPASS_URL = "https://overpass-api.de/api/interpreter"
_SEARCH_RADIUS_METERS = 5000
# Verified live: overpass-api.de's Apache config 406s a request with no User-Agent
# at all (httpx's default is empty) regardless of the query itself being valid —
# this exact header is required, not just good practice. The public instance is
# also genuinely slow under load (a plain nearby-hospitals query took ~15s in
# testing) — an aggressive short timeout here would make this silently no-op on
# most real requests, defeating the point of the feature; 10s is a compromise
# between that and still keeping the overall chat reply feeling responsive.
_REQUEST_HEADERS = {"User-Agent": "ClinicChatbot/1.0", "Accept": "*/*"}
_REQUEST_TIMEOUT_SECONDS = 10.0
_MAX_RESULTS = 3
_EARTH_RADIUS_KM = 6371.0


def _haversine_km(lat1: float, lng1: float, lat2: float, lng2: float) -> float:
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    d_phi = math.radians(lat2 - lat1)
    d_lambda = math.radians(lng2 - lng1)
    a = math.sin(d_phi / 2) ** 2 + math.cos(phi1) * math.cos(phi2) * math.sin(d_lambda / 2) ** 2
    return 2 * _EARTH_RADIUS_KM * math.asin(math.sqrt(a))


def _overpass_query(lat: float, lng: float) -> str:
    return (
        "[out:json][timeout:9];"
        "("
        f'node["amenity"="hospital"](around:{_SEARCH_RADIUS_METERS},{lat},{lng});'
        f'way["amenity"="hospital"](around:{_SEARCH_RADIUS_METERS},{lat},{lng});'
        ");"
        "out center tags;"
    )


def _element_coords(element: dict) -> tuple[float, float] | None:
    # Nodes carry lat/lon directly; ways/relations only carry it via "center"
    # (requested through "out center" above), since a way has no single point.
    if "lat" in element and "lon" in element:
        return element["lat"], element["lon"]
    center = element.get("center")
    if center and "lat" in center and "lon" in center:
        return center["lat"], center["lon"]
    return None


def _element_phone(tags: dict) -> str | None:
    return tags.get("phone") or tags.get("contact:phone")


def find_nearby_hospitals(lat: float, lng: float) -> list[dict]:
    """Returns up to _MAX_RESULTS hospitals sorted nearest-first, each a dict with
    name/distance_km/phone (phone is None when OSM has no tag for it). Returns an
    empty list on ANY failure (timeout, network error, no results) — never raises,
    since a failed lookup must never break the emergency reply itself."""
    try:
        response = httpx.post(
            _OVERPASS_URL,
            data={"data": _overpass_query(lat, lng)},
            headers=_REQUEST_HEADERS,
            timeout=_REQUEST_TIMEOUT_SECONDS,
        )
        response.raise_for_status()
        elements = response.json().get("elements", [])
    except (httpx.HTTPError, ValueError):
        return []

    hospitals = []
    for element in elements:
        tags = element.get("tags", {})
        name = tags.get("name")
        coords = _element_coords(element)
        if not name or coords is None:
            continue
        hospitals.append(
            {
                "name": name,
                "distance_km": _haversine_km(lat, lng, coords[0], coords[1]),
                "phone": _element_phone(tags),
            }
        )

    hospitals.sort(key=lambda h: h["distance_km"])
    return hospitals[:_MAX_RESULTS]


def nearby_hospitals_block(lat: float | None, lng: float | None) -> str:
    """Returns a plain-text block to append after an emergency reply, or "" when
    coordinates are missing or the lookup found nothing — an empty string is always
    safe to append (no stray blank lines/headers with nothing under them)."""
    if lat is None or lng is None:
        return ""

    hospitals = find_nearby_hospitals(lat, lng)
    if not hospitals:
        return ""

    lines = ["\n\nNearest emergency hospitals:"]
    for hospital in hospitals:
        phone_part = f" — {hospital['phone']}" if hospital["phone"] else " — phone not listed, call 1122"
        lines.append(f"- {hospital['name']} ({hospital['distance_km']:.1f} km away){phone_part}")
    return "\n".join(lines)
