"""Appends "nearest emergency hospital" info to an emergency reply, using the
patient's own device coordinates (sent by the frontend only at the moment a message
is about to be shown as an emergency reply — see app.schemas.chat.ChatRequest).

Data source is OpenStreetMap's public Overpass API — free, keyless, no signup, no
billing. Trade-off vs. a paid provider (Google Places etc.): coverage/data quality
varies by region, and a phone number isn't always tagged on a given hospital node.
Chosen anyway per product decision: this is a bolt-on convenience, not the emergency
instruction itself (the existing "call 1122" guidance already covers the safety-
critical part), so a paid API key is not worth the added operational cost.

Deliberately never allowed to block or degrade the actual emergency reply: a short
timeout, and ANY failure (no coordinates given, network error, empty result) simply
means the caller appends nothing — the emergency message text already fully stands
on its own without this block. Never generated by the LLM (same "don't trust the
LLM alone for a safety-critical fact" pattern as red_flag.py and appointment_agent's
doctor-name resolution) — this is a plain deterministic lookup + string format.
"""
import logging
import math

import httpx

logger = logging.getLogger(__name__)

# Reported live: worked reliably when called from a home/dev machine but came back
# empty on every request from the deployed Render backend, failing FAST (~3s, not
# anywhere near the timeout) — consistent with overpass-api.de rate-limiting or
# blocking requests from cloud-hosting IP ranges specifically (a known behavior of
# this free public instance, used to deter scraping), not a real network/timeout
# issue. Mitigated by trying a short list of independently-run public mirrors in
# order and using the first one that responds successfully, rather than depending
# on any single instance's cloud-IP policy.
#
# Ordered by what actually works from Render, not alphabetically or by
# popularity: overpass-api.de and overpass.kumi.systems have failed outright on
# EVERY real request logged from Render so far (ConnectError / ReadTimeout —
# looks like a genuine routing/blocking issue specific to Render's network, not a
# transient blip). Their FOSSGIS-hosted infrastructure (Germany) is a different
# problem from overpass.osm.ch, which connects fine from Render but was found
# (tested directly, even at a 50km radius) to carry NO Pakistan data at all — a
# regional/partial extract, not full-planet. maps.mail.ru's mirror was verified to
# have full real data for this exact area (83 elements, matching overpass-api.de's
# own count) and sits on entirely different infrastructure (Russia, not Germany),
# giving it a real chance of being reachable from Render where the .de-hosted ones
# aren't. Put first for that reason — the others stay as fallback in case Render's
# routing to any of them ever changes.
_OVERPASS_URLS = (
    "https://maps.mail.ru/osm/tools/overpass/api/interpreter",
    "https://overpass.osm.ch/api/interpreter",
    "https://overpass-api.de/api/interpreter",
    "https://overpass.kumi.systems/api/interpreter",
)
_SEARCH_RADIUS_METERS = 5000
# Verified live: overpass-api.de's Apache config 406s a request with no User-Agent
# at all (httpx's default is empty) regardless of the query itself being valid —
# this exact header is required, not just good practice.
#
# Kept deliberately short (not the ~10s a single mirror can need under load): this
# now tries up to 3 mirrors in sequence (see _OVERPASS_URLS above), so the worst
# case (every mirror slow/down) is this value times 3 — the patient is waiting on
# the ENTIRE emergency reply (base message + hospital block) during that whole
# window, since the guard is synchronous. A single mirror is far more likely to
# either answer quickly or fail/reject fast (blocked cloud IP, DNS failure) than to
# hang right up to a long timeout, so a short per-mirror budget loses little real
# coverage while capping the worst case at a bit over a normal LLM reply's own
# latency instead of dwarfing it.
_REQUEST_HEADERS = {"User-Agent": "ClinicChatbot/1.0", "Accept": "*/*"}
_REQUEST_TIMEOUT_SECONDS = 4.0
_MAX_RESULTS = 3
_EARTH_RADIUS_KM = 6371.0

# Reported live: a broken-leg emergency reply surfaced an eye hospital as the
# "nearest emergency hospital" — technically the closest amenity=hospital node, but
# useless for that patient, since a single-specialty hospital isn't equipped to
# treat an unrelated trauma case walking in. OSM's own emergency=yes tag (present
# on the SAME node, "does this place have a general emergency department") is the
# real signal to rank on, not raw distance — but it's community-edited and often
# missing even on hospitals that do have one, so it can only be used to PREFER a
# result, never to exclude the rest outright (a genuine nearest-hospital case with
# no tag at all must still show up rather than nothing). The name-keyword check
# below is a second, cruder signal for the same thing, for the (common) case where
# emergency=yes isn't tagged either way but the hospital's own name already gives
# away that it's a single-specialty facility a general/trauma emergency shouldn't
# be routed to.
_SPECIALTY_NAME_KEYWORDS = (
    "eye", "ophthalm", "dental", "dentistry", "maternity", "gynae", "obstetric",
    "children", "child ", "pediatric", "paediatric", "psychiatric", "mental health",
    "cancer", "oncology", "cardiac", "cardiology", "diabetic", "dermatology",
    "skin", "ent ", "e.n.t", "leprosy", "tb ", "tuberculosis", "chest disease",
    "rehabilitation", "physiotherapy", "homeopath", "dialysis",
)


def _is_specialty_named(name: str) -> bool:
    lowered = name.lower()
    return any(keyword in lowered for keyword in _SPECIALTY_NAME_KEYWORDS)


def _haversine_km(lat1: float, lng1: float, lat2: float, lng2: float) -> float:
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    d_phi = math.radians(lat2 - lat1)
    d_lambda = math.radians(lng2 - lng1)
    a = math.sin(d_phi / 2) ** 2 + math.cos(phi1) * math.cos(phi2) * math.sin(d_lambda / 2) ** 2
    return 2 * _EARTH_RADIUS_KM * math.asin(math.sqrt(a))


def _overpass_query(lat: float, lng: float) -> str:
    return (
        "[out:json][timeout:3];"
        "("
        f'node["amenity"="hospital"](around:{_SEARCH_RADIUS_METERS},{lat},{lng});'
        f'way["amenity"="hospital"](around:{_SEARCH_RADIUS_METERS},{lat},{lng});'
        ");"
        "out center tags;"
    )


def _element_coords(element: dict) -> tuple[float, float] | None:
    # Nodes carry lat/lon directly; ways/relations only carry it via "center"
    # (requested through "out center" above), since a way has no single point.
    if "lat" in element and "lon" in element:
        return element["lat"], element["lon"]
    center = element.get("center")
    if center and "lat" in center and "lon" in center:
        return center["lat"], center["lon"]
    return None


def _element_phone(tags: dict) -> str | None:
    return tags.get("phone") or tags.get("contact:phone")


# Reported live from Render's own logs: forcing local_address="0.0.0.0" (IPv4-only)
# turned mirror #1's error from "[Errno 101] Network is unreachable" into
# "[Errno -9] Address family for hostname not supported" — i.e. Render's resolver
# has no usable IPv4 address for that host at all, so forcing IPv4 didn't fix
# anything, it just changed which step failed. Reverted: forcing a specific family
# was a guess that turned out wrong, and risked breaking a mirror that might
# otherwise succeed over whichever family the OS's own dual-stack connection logic
# (which already tries every resolved address, not just the first) picks.
#
# except is intentionally broad (Exception, not just httpx.HTTPError/ValueError):
# reported live that mirror #3 produced neither a logged failure NOR a hospital
# block, meaning it very likely raised something outside that narrower tuple —
# never allowed to escape this function regardless of what it is, per this
# module's own "must never break the emergency reply" rule, but now always logged
# (including the exception's own type name) so a genuinely new failure mode shows
# up in Render's logs instead of vanishing silently again.
#
# Reported live: on Render, mirrors #1/#2 fail outright (see the comment above),
# so mirror #3 is effectively the only one that ever gets a chance — and it
# answered successfully but with ZERO elements for a real Lahore location that
# mirror #1 (from a different network) found 3 real hospitals for. Public Overpass
# mirrors are independently-run and don't all replicate from OSM at the same
# frequency, so coverage genuinely differs between them. An empty-but-successful
# response is therefore NOT treated as final here — it's remembered as a fallback,
# but every remaining mirror still gets tried in case one of them actually has
# data for this area; only returned if nothing else ever finds anything.
def _query_overpass(lat: float, lng: float) -> list[dict] | None:
    """Tries every mirror in _OVERPASS_URLS in order, returning the first
    NON-EMPTY successfully-parsed elements list. If every mirror either fails or
    succeeds with zero results, returns an empty list if at least one succeeded
    (a real "nothing nearby" answer), or None if every single one failed outright
    (a real lookup failure) — the caller treats both the same way (append
    nothing), but the distinction is preserved for logging clarity."""
    best_empty_result: list[dict] | None = None
    with httpx.Client(timeout=_REQUEST_TIMEOUT_SECONDS) as client:
        for url in _OVERPASS_URLS:
            try:
                response = client.post(url, data={"data": _overpass_query(lat, lng)}, headers=_REQUEST_HEADERS)
                response.raise_for_status()
                elements = response.json().get("elements", [])
                # WARNING, not INFO: the app never configures a root log level (no
                # logging.basicConfig anywhere), so INFO-level records are silently
                # dropped by Python's default WARNING threshold — reported live,
                # this line never appeared in Render's logs even on a real success,
                # making a genuine success indistinguishable from a silent failure.
                # Logged at WARNING purely so it's guaranteed visible under the
                # app's current logging setup, not because a success is a warning.
                logger.warning("nearby_hospitals: mirror %s succeeded with %d elements", url, len(elements))
                if elements:
                    return elements
                best_empty_result = elements
            except Exception as exc:
                logger.warning("nearby_hospitals: mirror %s failed: %s: %s", url, type(exc).__name__, exc)
    return best_empty_result


def find_nearby_hospitals(lat: float, lng: float) -> list[dict]:
    """Returns up to _MAX_RESULTS hospitals sorted nearest-first, each a dict with
    name/distance_km/phone (phone is None when OSM has no tag for it). Returns an
    empty list on ANY failure (every mirror down, network error, no results) —
    never raises, since a failed lookup must never break the emergency reply
    itself."""
    elements = _query_overpass(lat, lng)
    if elements is None:
        return []

    hospitals = []
    for element in elements:
        tags = element.get("tags", {})
        name = tags.get("name")
        coords = _element_coords(element)
        if not name or coords is None:
            continue
        hospitals.append(
            {
                "name": name,
                "distance_km": _haversine_km(lat, lng, coords[0], coords[1]),
                "phone": _element_phone(tags),
                # True when OSM explicitly confirms a general emergency department
                # (never inferred from absence of the tag — see _SPECIALTY_NAME_
                # KEYWORDS' own comment on why untagged still needs the name check).
                "has_emergency_dept": tags.get("emergency") == "yes",
                "is_specialty": _is_specialty_named(name),
            }
        )

    # Ranked general-emergency-capable-and-not-single-specialty first, then by
    # distance within each tier — never drops a hospital just for lacking the
    # emergency tag or reading as specialty-named, only reorders (see this
    # function's own module-level comment on why exclusion isn't safe here).
    hospitals.sort(key=lambda h: (h["is_specialty"], not h["has_emergency_dept"], h["distance_km"]))
    return hospitals[:_MAX_RESULTS]


def nearby_hospitals_block(lat: float | None, lng: float | None) -> str:
    """Returns a plain-text block to append after an emergency reply, or "" when
    coordinates are missing or the lookup found nothing — an empty string is always
    safe to append (no stray blank lines/headers with nothing under them)."""
    if lat is None or lng is None:
        return ""

    hospitals = find_nearby_hospitals(lat, lng)
    if not hospitals:
        return ""

    lines = ["\n\nNearest emergency hospitals:"]
    for hospital in hospitals:
        phone_part = f" — {hospital['phone']}" if hospital["phone"] else " — phone not listed, call 1122"
        lines.append(f"- {hospital['name']} ({hospital['distance_km']:.1f} km away){phone_part}")
    return "\n".join(lines)
