"""extend ingestion_logs for doctor csv ingestion

Revision ID: 1f983a79f8ce
Revises: cfa3b2a7866f
Create Date: 2026-07-20 14:33:50.391289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f983a79f8ce'
down_revision: Union[str, Sequence[str], None] = 'cfa3b2a7866f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_logs', sa.Column('source_type', sa.String(length=32), server_default='kb_document', nullable=False))
    op.add_column('ingestion_logs', sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True))
    op.add_column('ingestion_logs', sa.Column('filename', sa.String(length=255), nullable=True))
    op.add_column('ingestion_logs', sa.Column('rows_accepted', sa.Integer(), nullable=True))
    op.add_column('ingestion_logs', sa.Column('rows_rejected', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ingestion_logs', 'users', ['uploaded_by_user_id'], ['id'])
    op.create_check_constraint(
        'ck_ingestion_logs_source_type', 'ingestion_logs', "source_type IN ('kb_document', 'doctor_csv')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_ingestion_logs_source_type', 'ingestion_logs', type_='check')
    op.drop_constraint(None, 'ingestion_logs', type_='foreignkey')
    op.drop_column('ingestion_logs', 'rows_rejected')
    op.drop_column('ingestion_logs', 'rows_accepted')
    op.drop_column('ingestion_logs', 'filename')
    op.drop_column('ingestion_logs', 'uploaded_by_user_id')
    op.drop_column('ingestion_logs', 'source_type')
    # ### end Alembic commands ###
