"""add chunk_count to kb_documents

Revision ID: cfa3b2a7866f
Revises: 7ac61d870ef1
Create Date: 2026-07-20 13:35:31.694029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa3b2a7866f'
down_revision: Union[str, Sequence[str], None] = '7ac61d870ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_documents', sa.Column('chunk_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kb_documents', 'chunk_count')
    # ### end Alembic commands ###
